<a href="https://colab.research.google.com/github/MUDULURUGAYATHRIVARMA/Movie_recommendation_system/blob/main/MovieRecommendationSystem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as ny
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [8]:
moviesdata=pd.read_csv('/content/movies.csv')

In [9]:
moviesdata.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [10]:
moviesdata.shape

(4803, 24)

In [11]:
selected_features=['genres','keywords','tagline','cast','director','overview']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director', 'overview']


In [12]:
#fillna() method will replaces null values with specified valus
for feature in selected_features:
  moviesdata[feature]=moviesdata[feature].fillna('')

In [13]:
combine_selected_features=moviesdata['genres']+' '+moviesdata['keywords']+' '+moviesdata['tagline']+' '+moviesdata['cast']+' '+moviesdata['director']+' '+moviesdata['overview']

In [14]:
print(combine_selected_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      A New Yorker in Shanghai Daniel Henney Eliza...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


In [15]:
#converting the text to feature vector (numeric values) beacause with help of numeric values we can easily find the cosine similarity
vectorizer=TfidfVectorizer()

In [16]:
feature_vector = vectorizer.fit_transform(combine_selected_features)
print(feature_vector)

  (0, 561)	0.05971816344971169
  (0, 703)	0.06846420517510078
  (0, 9754)	0.08513696797398294
  (0, 23977)	0.07941905576010944
  (0, 10023)	0.07960231361105431
  (0, 6601)	0.1498786462809525
  (0, 5279)	0.1549075340655008
  (0, 10796)	0.11095111375730655
  (0, 25413)	0.24369151759694266
  (0, 29469)	0.08637114089261566
  (0, 5592)	0.17322386697661618
  (0, 25232)	0.1336739112380023
  (0, 9065)	0.14505772980982928
  (0, 27118)	0.08328687324810813
  (0, 30121)	0.07272849549697494
  (0, 19410)	0.0318696249813729
  (0, 20039)	0.37747447361884223
  (0, 23619)	0.11047375838269538
  (0, 30145)	0.18243919685121024
  (0, 30543)	0.15064979633862852
  (0, 23578)	0.16802034155542864
  (0, 24802)	0.158925784923944
  (0, 29614)	0.15064979633862852
  (0, 25868)	0.11590870590502833
  (0, 15569)	0.171366691592621
  :	:
  (4802, 9588)	0.10415492266309316
  (4802, 21386)	0.08975511036766048
  (4802, 9166)	0.07829183421073847
  (4802, 24102)	0.08207980733784753
  (4802, 6136)	0.10774075928383217
  (4802, 

In [17]:
#to find similarity between user input and dataset we use cosine similarity
similarity=cosine_similarity(feature_vector)
print(similarity)

[[1.         0.05083168 0.0332947  ... 0.02749812 0.0304889  0.0072518 ]
 [0.05083168 1.         0.04356836 ... 0.05077045 0.03100979 0.01521198]
 [0.0332947  0.04356836 1.         ... 0.02646984 0.04751623 0.01372603]
 ...
 [0.02749812 0.05077045 0.02646984 ... 1.         0.03481447 0.03546821]
 [0.0304889  0.03100979 0.04751623 ... 0.03481447 1.         0.03098945]
 [0.0072518  0.01521198 0.01372603 ... 0.03546821 0.03098945 1.        ]]


In [18]:
print(similarity.shape)

(4803, 4803)


In [19]:
#now getting input from user
moviename=input("Enter your any movie name:")

Enter your any movie name:avatar


In [20]:
#now taking only list of all movie names to compare with user input
list_movies=moviesdata['title'].tolist()
print(list_movies)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [21]:
# now we are going to find similar or closer to movie tilte with user input
finding_close_movie=difflib.get_close_matches(moviename,list_movies)
print(finding_close_movie)

['Avatar']


In [22]:
close_match=finding_close_movie[0]
print(close_match)

Avatar


In [23]:
#finding index of movie by using title of movie
index_of_movie=moviesdata[moviesdata.title==close_match]['index'].values[0]
print(index_of_movie)

0


In [24]:
# find similar movies based on index values
similarity_score=list(enumerate(similarity[index_of_movie]))
print(similarity_score)


[(0, 1.0000000000000004), (1, 0.050831680232069756), (2, 0.03329469936108888), (3, 0.03480071555037372), (4, 0.0872468663089366), (5, 0.0566969483263915), (6, 0.022512258494852992), (7, 0.067737097155122), (8, 0.021355368766540147), (9, 0.033355412411909396), (10, 0.05173124937993884), (11, 0.035507529604099794), (12, 0.022408760244619012), (13, 0.029840631369536713), (14, 0.06234629311654264), (15, 0.0348600875881102), (16, 0.04270511084643852), (17, 0.033016644150654), (18, 0.0623433305067024), (19, 0.03758892805682068), (20, 0.032415446931791166), (21, 0.022573109365739863), (22, 0.023383368657539157), (23, 0.03815117320234565), (24, 0.028065465565668926), (25, 0.03954093319213128), (26, 0.0774460607460518), (27, 0.09086096153920842), (28, 0.028921214453158286), (29, 0.052157920575958555), (30, 0.04679198413957892), (31, 0.07369439017469571), (32, 0.044169525398501296), (33, 0.032543980146555726), (34, 0.01822898676468554), (35, 0.058686160027715), (36, 0.08506438514870909), (37, 0.

In [25]:
len(similarity_score)

4803

In [26]:
#sorting the movies acording to their similarities
sorting_movies=sorted(similarity_score,key=lambda x:x[1],reverse=True)
print(sorting_movies)

[(0, 1.0000000000000004), (1914, 0.16126755021560368), (1531, 0.15947661416113432), (3158, 0.15353580040499362), (56, 0.15169213117081481), (1352, 0.1493808565720171), (2403, 0.14835180763632994), (94, 0.1415140341440704), (239, 0.133557022428701), (2198, 0.13162057575067118), (3604, 0.12928261800464524), (461, 0.12876702330020762), (3730, 0.1269519487017688), (369, 0.12601494004493413), (305, 0.12432028150650486), (342, 0.12374180568725782), (47, 0.12367872604116287), (661, 0.12296563604922994), (942, 0.12234596060863667), (1275, 0.12224354634574007), (150, 0.11975427140900297), (1354, 0.11884216977680731), (4401, 0.1183184319593006), (300, 0.11678308373871148), (432, 0.11587675428201633), (529, 0.11423470366536428), (1759, 0.11402805386153822), (549, 0.11354716615947666), (43, 0.11324250877132762), (2995, 0.11218183545630812), (311, 0.11160871159754028), (4332, 0.11149904057704482), (2696, 0.11109265691024968), (4593, 0.11014673956791823), (1053, 0.10989684187615316), (775, 0.1090105

In [27]:
# now we are printing all similar movies using  their index
print("These are few relevent movie_titles according to your search:\n")
i=1
for movie in sorting_movies:
  index = movie[0]
  total_movies=moviesdata[moviesdata.index==index]['title'].values[0]
  if(i<=30):
    print(i,'.',total_movies)
    i+=1




These are few relevent movie_titles according to your search:

1 . Avatar
2 . Lifeforce
3 . Moonraker
4 . Alien
5 . Star Trek Beyond
6 . Gattaca
7 . Aliens
8 . Guardians of the Galaxy
9 . Gravity
10 . Lockout
11 . Apollo 18
12 . Lost in Space
13 . Cargo
14 . Lara Croft Tomb Raider: The Cradle of Life
15 . Treasure Planet
16 . Men in Black
17 . Star Trek Into Darkness
18 . Zathura: A Space Adventure
19 . The Book of Life
20 . Sunshine
21 . Men in Black II
22 . Space Chimps
23 . The Helix... Loaded
24 . Starship Troopers
25 . Deep Impact
26 . Tears of the Sun
27 . The Right Stuff
28 . Sphere
29 . Terminator Salvation
30 . Mad Max Beyond Thunderdome


Movie Recommendation System


In [28]:
moviename=input("Enter your any movie name:")

list_movies=moviesdata['title'].tolist()

finding_close_movie=difflib.get_close_matches(moviename,list_movies)

close_match=finding_close_movie[0]

index_of_movie=moviesdata[moviesdata.title==close_match]['index'].values[0]

similarity_score=list(enumerate(similarity[index_of_movie]))

sorting_movies=sorted(similarity_score,key=lambda x:x[1],reverse=True)

print("\nThese are few relevent movie_titles according to your search:\n")
i=1
for movie in sorting_movies:
  index = movie[0]
  total_movies=moviesdata[moviesdata.index==index]['title'].values[0]
  if(i<=30):
    print(i,'.',total_movies)
    i+=1



Enter your any movie name:avenger 

These are few relevent movie_titles according to your search:

1 . The Avengers
2 . Avengers: Age of Ultron
3 . Captain America: The Winter Soldier
4 . Iron Man 2
5 . Captain America: Civil War
6 . X-Men
7 . The Incredible Hulk
8 . Thor: The Dark World
9 . X-Men: Apocalypse
10 . Captain America: The First Avenger
11 . X-Men: Days of Future Past
12 . Ant-Man
13 . Iron Man 3
14 . X-Men: The Last Stand
15 . Iron Man
16 . X-Men: First Class
17 . Thor
18 . X2
19 . Man of Steel
20 . The Amazing Spider-Man 2
21 . Kick-Ass
22 . Superman II
23 . Serenity
24 . Guardians of the Galaxy
25 . The Shadow
26 . Fantastic 4: Rise of the Silver Surfer
27 . Deadpool
28 . The Losers
29 . The Spirit
30 . The Horse Whisperer
